sonar.projectKey=sudhakar-dotcom_safeci
sonar.organization=sudhakar-dotcom
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/.git/**,**/.leaky-meta/**
